- name: 创建kubelet_path,cni_path目录
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ kubelet_path }}"
    - "{{ cni_path }}"

- name: 分发kubelet
  copy:
    src: files/kubelet
    dest: "{{ kubelet_path }}"
    directory_mode: 755
    mode: u+x

- name: 分发cni
  unarchive:
    src: files/{{ cni_tar }}
    dest: "{{ cni_path }}"
    mode: u+x

- name: 分发kubectl到Master
  copy:
    src: files/kubectl
    dest: "{{ kubectl_path }}"
    directory_mode: 755
    mode: u+x

- include: cfssl.yml
  delegate_to: "{{ groups['master1'][0] }}"
  run_once: true
